<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MessageController;

// Student Controllers
use App\Http\Controllers\Student\DashboardController as StudentDashboardController;
use App\Http\Controllers\Student\FindTutorController;

// Tutor Controllers
use App\Http\Controllers\Tutor\DashboardController as TutorDashboardController;
use App\Http\Controllers\Tutor\TutorProfileController;

// Admin Controllers
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\TutorManagementController;
use App\Http\Controllers\Admin\StudentManagementController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Home Page Route
Route::get('/', function () {
    return view('home');
});

// Main Dashboard Redirector
Route::get('/dashboard', function () {
    if (!Auth::check()) {
        return redirect('/login');
    }
    $role = Auth::user()->role;
    if ($role === 'student') {
        return redirect()->route('student.dashboard');
    } elseif ($role === 'tutor') {
        return redirect()->route('tutor.dashboard');
    } elseif ($role === 'admin') {
        return redirect()->route('admin.dashboard');
    }
    return redirect('/');
})->middleware(['auth', 'verified'])->name('dashboard');


// ----- PROTECTED ROUTES -----

// Student Routes
Route::middleware(['auth', 'role:student'])->prefix('student')->name('student.')->group(function () {
    Route::get('/dashboard', [StudentDashboardController::class, 'index'])->name('dashboard');
    Route::get('/tutors', [FindTutorController::class, 'index'])->name('tutors.index');
    Route::get('/tutors/{user}', [FindTutorController::class, 'show'])->name('tutors.show');
});

// Tutor Routes
Route::middleware(['auth', 'role:tutor'])->prefix('tutor')->name('tutor.')->group(function () {
    Route::get('/dashboard', [TutorDashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [TutorProfileController::class, 'edit'])->name('profile.edit');
    Route::post('/profile', [TutorProfileController::class, 'update'])->name('profile.update');
});

// Admin Routes
Route::middleware(['auth', 'role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    Route::get('/tutors', [TutorManagementController::class, 'index'])->name('tutors.index');
    Route::patch('/tutors/{user}/status', [TutorManagementController::class, 'updateStatus'])->name('tutors.updateStatus');
    Route::get('/students', [StudentManagementController::class, 'index'])->name('students.index');
});


// Routes available to any authenticated user
Route::middleware('auth')->group(function () {
    Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
    Route::post('/messages', [MessageController::class, 'store'])->name('messages.store');

    // Default profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});


// Include the authentication routes generated by Breeze
require __DIR__.'/auth.php';